# Generated by Django 3.2.18 on 2023-03-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('birth_date', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('primary_skill', models.JSONField()),
                ('secondary_skill', models.JSONField()),
                ('company', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
