# Generated by Django 3.2.18 on 2023-03-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_primary_skill_provider_primary_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
